import upperFirst from 'lodash.upperfirst'
import { PinionContext, renderTemplate, toFile, prompt } from '@featherscloud/pinion'

interface Context extends PinionContext {
  bio: string
  docsPath: string
  name: string
}

export function licenseTemplate() {
  return `Creative Commons (CC) ${new Date().getFullYear()}`
}

// A template for a markdown Doc file
const author = ({ name, bio }: Context) => {
  return `# Hello ${upperFirst(name)}!!

This is a doc generated by Me.

About me: ${bio}

${licenseTemplate()}
`
}

export const generate = (init: Context) => {
  return Promise.resolve(init)
    .then(
      prompt({
        name: {
          type: 'input',
          message: 'What is your name?'
        },
        bio: {
          type: 'input',
          message: 'Talk us about you:'
        },
        docsPath: {
          type: 'input',
          message: 'Where should be this doc?'
        }
      })
    )
    // Render the readme template
    .then(renderTemplate(author, toFile(context => [context.docsPath, 'author.md'])))
}